@Pixeval.Backend_HostAddress = https://localhost:7259
@UserId = userId=104757871
@IllustrationId = illustrationId=118098663
@FollowedUserId = followedUserId=502358

### 收藏列表

GET {{Pixeval.Backend_HostAddress}}/favorite/list?{{UserId}}

### 收藏

POST {{Pixeval.Backend_HostAddress}}/favorite?{{UserId}}&{{IllustrationId}}&favorite=true

### 取消收藏

POST {{Pixeval.Backend_HostAddress}}/favorite?{{UserId}}&{{IllustrationId}}&favorite=false

### 错误：收藏请求

POST {{Pixeval.Backend_HostAddress}}/favorite?{{UserId}}&illustrationId=0&favorite=false

### 关注列表

GET {{Pixeval.Backend_HostAddress}}/follow/list?{{UserId}}

### 关注

POST {{Pixeval.Backend_HostAddress}}/follow?{{UserId}}&{{FollowedUserId}}&follow=true

### 取消关注

POST {{Pixeval.Backend_HostAddress}}/follow?{{UserId}}&{{FollowedUserId}}&follow=false

### 推荐作品

GET {{Pixeval.Backend_HostAddress}}/recommendation/illustrations?{{UserId}}

### 推荐用户

GET {{Pixeval.Backend_HostAddress}}/recommendation/users?{{UserId}}

### 排行

GET {{Pixeval.Backend_HostAddress}}/ranking?{{UserId}}

### 关注新作

GET {{Pixeval.Backend_HostAddress}}/newworks?{{UserId}}

### 全部新作

GET {{Pixeval.Backend_HostAddress}}/newworks/all?{{UserId}}

### 获取作品

GET {{Pixeval.Backend_HostAddress}}/get/illustration?{{UserId}}&{{IllustrationId}}

### 获取用户

GET {{Pixeval.Backend_HostAddress}}/get/user?{{UserId}}&{{FollowedUserId}}
